version: '3.8'

services:
  backend:
    build: ./
    container_name: todo-backend-bab
    ports:
      - "3001:3000"
    env_file:
      - ./.env # Load environment variables
    environment:
      MONGO_URI: "mongodb://mongo:27017/todo"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - frontend

  frontend:
    build: ./app
    container_name: todo-frontend-bab
    ports:
      - "3000:80"
    volumes:
      - ./app:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: todo-mongo-bab
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
