# docker-compose.yml
# version: "3.8"

services:
  fullstack_backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todo-backend-bab
    ports:
      - "3001:3000"
    env_file:
      - ./.env # Load environment variables
    # environment:
    #   MONGO_URI: "mongodb://mongo:27017/todo"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: todo-mongo-bab
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
